name: MACD Bot Alert

on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  workflow_dispatch:     # manual trigger option

jobs:
  run-macd-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID_MACD: ${{ secrets.TELEGRAM_CHAT_ID_MACD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Run MACD bot
        run: python macd_bot/macd_bot.py
